/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerdictUsernameRouteImport } from './routes/verdict.$username'
import { Route as ShareUsernameRouteImport } from './routes/share.$username'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as OgSiteRouteImport } from './routes/og.site'
import { Route as OgUsernameRouteImport } from './routes/og.$username'
import { Route as FilmImdbIdRouteImport } from './routes/film.$imdbId'
import { Route as ProfileUsernameIndexRouteImport } from './routes/profile.$username.index'
import { Route as ProfileUsernameFollowingRouteImport } from './routes/profile.$username.following'
import { Route as ProfileUsernameFollowersRouteImport } from './routes/profile.$username.followers'
import { Route as OgErrorCodeRouteImport } from './routes/og.error.$code'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerdictUsernameRoute = VerdictUsernameRouteImport.update({
  id: '/verdict/$username',
  path: '/verdict/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareUsernameRoute = ShareUsernameRouteImport.update({
  id: '/share/$username',
  path: '/share/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const OgSiteRoute = OgSiteRouteImport.update({
  id: '/og/site',
  path: '/og/site',
  getParentRoute: () => rootRouteImport,
} as any)
const OgUsernameRoute = OgUsernameRouteImport.update({
  id: '/og/$username',
  path: '/og/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmImdbIdRoute = FilmImdbIdRouteImport.update({
  id: '/film/$imdbId',
  path: '/film/$imdbId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameIndexRoute = ProfileUsernameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileUsernameRoute,
} as any)
const ProfileUsernameFollowingRoute =
  ProfileUsernameFollowingRouteImport.update({
    id: '/following',
    path: '/following',
    getParentRoute: () => ProfileUsernameRoute,
  } as any)
const ProfileUsernameFollowersRoute =
  ProfileUsernameFollowersRouteImport.update({
    id: '/followers',
    path: '/followers',
    getParentRoute: () => ProfileUsernameRoute,
  } as any)
const OgErrorCodeRoute = OgErrorCodeRouteImport.update({
  id: '/og/error/$code',
  path: '/og/error/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/film/$imdbId': typeof FilmImdbIdRoute
  '/og/$username': typeof OgUsernameRoute
  '/og/site': typeof OgSiteRoute
  '/profile/$username': typeof ProfileUsernameRouteWithChildren
  '/share/$username': typeof ShareUsernameRoute
  '/verdict/$username': typeof VerdictUsernameRoute
  '/og/error/$code': typeof OgErrorCodeRoute
  '/profile/$username/followers': typeof ProfileUsernameFollowersRoute
  '/profile/$username/following': typeof ProfileUsernameFollowingRoute
  '/profile/$username/': typeof ProfileUsernameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/film/$imdbId': typeof FilmImdbIdRoute
  '/og/$username': typeof OgUsernameRoute
  '/og/site': typeof OgSiteRoute
  '/share/$username': typeof ShareUsernameRoute
  '/verdict/$username': typeof VerdictUsernameRoute
  '/og/error/$code': typeof OgErrorCodeRoute
  '/profile/$username/followers': typeof ProfileUsernameFollowersRoute
  '/profile/$username/following': typeof ProfileUsernameFollowingRoute
  '/profile/$username': typeof ProfileUsernameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/film/$imdbId': typeof FilmImdbIdRoute
  '/og/$username': typeof OgUsernameRoute
  '/og/site': typeof OgSiteRoute
  '/profile/$username': typeof ProfileUsernameRouteWithChildren
  '/share/$username': typeof ShareUsernameRoute
  '/verdict/$username': typeof VerdictUsernameRoute
  '/og/error/$code': typeof OgErrorCodeRoute
  '/profile/$username/followers': typeof ProfileUsernameFollowersRoute
  '/profile/$username/following': typeof ProfileUsernameFollowingRoute
  '/profile/$username/': typeof ProfileUsernameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/feed'
    | '/login'
    | '/search'
    | '/signup'
    | '/sitemap.xml'
    | '/film/$imdbId'
    | '/og/$username'
    | '/og/site'
    | '/profile/$username'
    | '/share/$username'
    | '/verdict/$username'
    | '/og/error/$code'
    | '/profile/$username/followers'
    | '/profile/$username/following'
    | '/profile/$username/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/feed'
    | '/login'
    | '/search'
    | '/signup'
    | '/sitemap.xml'
    | '/film/$imdbId'
    | '/og/$username'
    | '/og/site'
    | '/share/$username'
    | '/verdict/$username'
    | '/og/error/$code'
    | '/profile/$username/followers'
    | '/profile/$username/following'
    | '/profile/$username'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/feed'
    | '/login'
    | '/search'
    | '/signup'
    | '/sitemap.xml'
    | '/film/$imdbId'
    | '/og/$username'
    | '/og/site'
    | '/profile/$username'
    | '/share/$username'
    | '/verdict/$username'
    | '/og/error/$code'
    | '/profile/$username/followers'
    | '/profile/$username/following'
    | '/profile/$username/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  FeedRoute: typeof FeedRoute
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  FilmImdbIdRoute: typeof FilmImdbIdRoute
  OgUsernameRoute: typeof OgUsernameRoute
  OgSiteRoute: typeof OgSiteRoute
  ProfileUsernameRoute: typeof ProfileUsernameRouteWithChildren
  ShareUsernameRoute: typeof ShareUsernameRoute
  VerdictUsernameRoute: typeof VerdictUsernameRoute
  OgErrorCodeRoute: typeof OgErrorCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verdict/$username': {
      id: '/verdict/$username'
      path: '/verdict/$username'
      fullPath: '/verdict/$username'
      preLoaderRoute: typeof VerdictUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$username': {
      id: '/share/$username'
      path: '/share/$username'
      fullPath: '/share/$username'
      preLoaderRoute: typeof ShareUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/site': {
      id: '/og/site'
      path: '/og/site'
      fullPath: '/og/site'
      preLoaderRoute: typeof OgSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/$username': {
      id: '/og/$username'
      path: '/og/$username'
      fullPath: '/og/$username'
      preLoaderRoute: typeof OgUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/film/$imdbId': {
      id: '/film/$imdbId'
      path: '/film/$imdbId'
      fullPath: '/film/$imdbId'
      preLoaderRoute: typeof FilmImdbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username/': {
      id: '/profile/$username/'
      path: '/'
      fullPath: '/profile/$username/'
      preLoaderRoute: typeof ProfileUsernameIndexRouteImport
      parentRoute: typeof ProfileUsernameRoute
    }
    '/profile/$username/following': {
      id: '/profile/$username/following'
      path: '/following'
      fullPath: '/profile/$username/following'
      preLoaderRoute: typeof ProfileUsernameFollowingRouteImport
      parentRoute: typeof ProfileUsernameRoute
    }
    '/profile/$username/followers': {
      id: '/profile/$username/followers'
      path: '/followers'
      fullPath: '/profile/$username/followers'
      preLoaderRoute: typeof ProfileUsernameFollowersRouteImport
      parentRoute: typeof ProfileUsernameRoute
    }
    '/og/error/$code': {
      id: '/og/error/$code'
      path: '/og/error/$code'
      fullPath: '/og/error/$code'
      preLoaderRoute: typeof OgErrorCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProfileUsernameRouteChildren {
  ProfileUsernameFollowersRoute: typeof ProfileUsernameFollowersRoute
  ProfileUsernameFollowingRoute: typeof ProfileUsernameFollowingRoute
  ProfileUsernameIndexRoute: typeof ProfileUsernameIndexRoute
}

const ProfileUsernameRouteChildren: ProfileUsernameRouteChildren = {
  ProfileUsernameFollowersRoute: ProfileUsernameFollowersRoute,
  ProfileUsernameFollowingRoute: ProfileUsernameFollowingRoute,
  ProfileUsernameIndexRoute: ProfileUsernameIndexRoute,
}

const ProfileUsernameRouteWithChildren = ProfileUsernameRoute._addFileChildren(
  ProfileUsernameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  FeedRoute: FeedRoute,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  FilmImdbIdRoute: FilmImdbIdRoute,
  OgUsernameRoute: OgUsernameRoute,
  OgSiteRoute: OgSiteRoute,
  ProfileUsernameRoute: ProfileUsernameRouteWithChildren,
  ShareUsernameRoute: ShareUsernameRoute,
  VerdictUsernameRoute: VerdictUsernameRoute,
  OgErrorCodeRoute: OgErrorCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
