/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerdictUsernameRouteImport } from './routes/verdict.$username'
import { Route as ShareUsernameRouteImport } from './routes/share.$username'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerdictUsernameRoute = VerdictUsernameRouteImport.update({
  id: '/verdict/$username',
  path: '/verdict/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareUsernameRoute = ShareUsernameRouteImport.update({
  id: '/share/$username',
  path: '/share/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/share/$username': typeof ShareUsernameRoute
  '/verdict/$username': typeof VerdictUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/share/$username': typeof ShareUsernameRoute
  '/verdict/$username': typeof VerdictUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/share/$username': typeof ShareUsernameRoute
  '/verdict/$username': typeof VerdictUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/feed'
    | '/login'
    | '/sitemap.xml'
    | '/profile/$username'
    | '/share/$username'
    | '/verdict/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feed'
    | '/login'
    | '/sitemap.xml'
    | '/profile/$username'
    | '/share/$username'
    | '/verdict/$username'
  id:
    | '__root__'
    | '/'
    | '/feed'
    | '/login'
    | '/sitemap.xml'
    | '/profile/$username'
    | '/share/$username'
    | '/verdict/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeedRoute: typeof FeedRoute
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  ShareUsernameRoute: typeof ShareUsernameRoute
  VerdictUsernameRoute: typeof VerdictUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verdict/$username': {
      id: '/verdict/$username'
      path: '/verdict/$username'
      fullPath: '/verdict/$username'
      preLoaderRoute: typeof VerdictUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$username': {
      id: '/share/$username'
      path: '/share/$username'
      fullPath: '/share/$username'
      preLoaderRoute: typeof ShareUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeedRoute: FeedRoute,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  ShareUsernameRoute: ShareUsernameRoute,
  VerdictUsernameRoute: VerdictUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
